import {
  Utensils,
  Scissors,
  Ship,
  Heart,
  Flag,
  Trophy,
  Home,
  Stethoscope,
  ShoppingBag,
  GraduationCap,
  Briefcase,
  Wrench,
  Siren,
  Sparkles,
  Dumbbell,
  Wine,
  Calendar,
  Anchor,
  Building,
  Mountain,
  Tag,
  Coffee,
  Bed,
  Car,
  PawPrint,
  Laptop,
  Landmark,
  Pill,
  Scale,
  Calculator,
  TrendingUp,
  Flower2,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  utensils: Utensils,
  scissors: Scissors,
  ship: Ship,
  heart: Heart,
  flag: Flag,
  trophy: Trophy,
  home: Home,
  stethoscope: Stethoscope,
  'shopping-bag': ShoppingBag,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  wrench: Wrench,
  siren: Siren,
  sparkles: Sparkles,
  dumbbell: Dumbbell,
  wine: Wine,
  calendar: Calendar,
  anchor: Anchor,
  building: Building,
  mountain: Mountain,
  tag: Tag,
  coffee: Coffee,
  bed: Bed,
  car: Car,
  'paw-print': PawPrint,
  laptop: Laptop,
  landmark: Landmark,
  pill: Pill,
  scale: Scale,
  calculator: Calculator,
  'trending-up': TrendingUp,
  'flower-2': Flower2,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Tag;
}
