/*
  # Add FAQs for new beach, hiking, and bike trail guides

  1. New FAQs
    - 5 FAQs for beaches guides
    - 5 FAQs for hiking guides
    - 5 FAQs for bike guides

  2. SEO
    - Question-based keywords targeting voice search queries
    - High-intent local search terms
*/

INSERT INTO faqs (page_type, page_slug, question, answer, display_order)
VALUES
  ('guide', 'complete-beach-guide-calvia', 'Are the beaches in Calvia free to visit?', 'Yes, all beaches in Calvia are free to access. There is no entrance fee for any public beach. However, sunbed and umbrella rental typically costs around 13 EUR for two loungers with parasol at main beaches like Palmanova and Santa Ponsa. Hidden coves have no rental facilities.', 1),
  ('guide', 'complete-beach-guide-calvia', 'Which is the best beach in Calvia for snorkelling?', 'Cala Vinyes and Cala Fornells offer the best snorkelling conditions in Calvia, with clear water and diverse rock formations supporting marine life. Cala Portals Vells is also excellent, with underwater caves to explore. Always snorkel on calm days for the best visibility.', 2),
  ('guide', 'complete-beach-guide-calvia', 'Are there lifeguards on Calvia beaches?', 'Lifeguards are present on the main beaches (Palmanova, Santa Ponsa, Peguera, Magaluf, Illetas) from May to October. Smaller coves and hidden beaches do not have lifeguard services. Always check the flag system: green (safe), yellow (caution), red (no swimming).', 3),
  ('guide', 'complete-beach-guide-calvia', 'Can I reach hidden coves in Calvia without a car?', 'The main beaches (Palmanova, Magaluf, Santa Ponsa, Peguera) are accessible by public bus from Palma. However, hidden coves like Cala Falco, Cala del Mago, and Ses Penyes Roges require a car or taxi to reach the trailhead, plus a walk to the beach.', 4),
  ('guide', 'complete-beach-guide-calvia', 'When is the best time to visit beaches in Calvia?', 'The swimming season runs from May to October. June and September offer the best combination of warm water, pleasant temperatures, and fewer crowds. July and August are hottest and busiest. For hidden coves, spring and autumn provide peaceful visits with pleasant weather.', 5),
  ('guide', 'family-beaches-calvia', 'Which Calvia beach is safest for toddlers?', 'Palmanova Beach offers the safest conditions for toddlers: very shallow, gradual entry with calm waters, lifeguards from May to October, and a wide sandy shoreline. The promenade provides pushchair access and nearby restaurants for family meals.', 1),
  ('guide', 'family-beaches-calvia', 'Do Calvia beaches have changing facilities for babies?', 'Main beaches like Palmanova, Santa Ponsa, and Peguera have public toilet and shower facilities. However, dedicated baby changing rooms are limited -- many parents use beach tents for changing. Restaurants along the promenades often have baby-friendly facilities.', 2),
  ('guide', 'hidden-coves-secret-beaches-calvia', 'Is Cala del Mago a nudist beach?', 'Yes, Cala del Mago is a clothing-optional (nudist-friendly) beach. It is one of the few designated nudist spots in Calvia. The beach has no facilities, so bring everything you need including water, food, and sun protection.', 1),
  ('guide', 'hidden-coves-secret-beaches-calvia', 'How do I get to the hidden coves in Calvia?', 'Most hidden coves require driving to a nearby car park then walking 10-30 minutes on rocky coastal trails. Sturdy footwear is essential. Popular starting points include Portals Vells car park (for Cala del Mago and Portals Vells) and Peguera (for Cala Fornells and Calo den Monjo).', 2),
  ('guide', 'complete-hiking-guide-calvia', 'Do I need hiking boots for trails in Calvia?', 'For easy trails like Enjoy Peguera and Torrent de Santa Ponca, comfortable trainers are sufficient. For medium trails like CR1 to Cap Andritxol, proper hiking shoes with grip are recommended. For mountain trails like Puig de Galatzo and GR221 sections, ankle-supporting hiking boots are essential.', 1),
  ('guide', 'complete-hiking-guide-calvia', 'Is the Puig de Galatzo hike dangerous?', 'The Puig de Galatzo hike is challenging but not dangerous for prepared, fit hikers in good conditions. The risks come from extreme heat in summer, poor visibility in fog or rain, and the exposed rocky summit. Start early, check weather forecasts, carry 2L water minimum, and tell someone your route plan.', 2),
  ('guide', 'complete-hiking-guide-calvia', 'Are dogs allowed on hiking trails in Calvia?', 'Dogs are allowed on most hiking trails in Calvia but must be kept on a lead. Be aware of pine processionary caterpillars (January-April) which are extremely toxic to dogs. Carry extra water for your dog and avoid trails during the hottest part of the day in summer.', 3),
  ('guide', 'complete-hiking-guide-calvia', 'What is the best hiking app for Calvia trails?', 'Wikiloc and AllTrails are the most popular hiking apps for Calvia, with GPS routes uploaded by local hikers. Komoot is also excellent for route planning. Always download routes for offline use before setting out, as mobile signal can be poor in mountain areas.', 4),
  ('guide', 'easy-family-walks-calvia', 'Can I walk the Enjoy Peguera Trail with a pushchair?', 'The first kilometre of the Enjoy Peguera Trail is paved and suitable for standard pushchairs. Beyond that, the trail becomes a packed earth path that is manageable with all-terrain pushchairs but not with standard wheels. Baby carriers are recommended for the full loop.', 1),
  ('guide', 'complete-cycling-guide-calvia', 'Can I rent bikes in Calvia?', 'Yes, several bike rental shops operate in Calvia, particularly in Peguera, Santa Ponsa, and Palmanova. Standard bikes cost from 12 EUR per day, road bikes from 25 EUR, and e-bikes from 35 EUR. Most shops include helmets, locks, and basic repair kits in the rental.', 1),
  ('guide', 'complete-cycling-guide-calvia', 'Are helmets required for cycling in Calvia?', 'Helmets are mandatory for cyclists under 16 in Spain. For adults, helmets are not legally required on urban roads but are strongly recommended, especially on mountain descents where speeds can exceed 60 km/h. Most rental shops include helmets.', 2),
  ('guide', 'complete-cycling-guide-calvia', 'What is the best time of year for cycling in Calvia?', 'February to May and September to November offer ideal cycling conditions: temperatures between 15-25C, dry roads, and manageable winds. Professional teams train here in January-March. Summer (June-August) is too hot for afternoon riding -- start before 8am if cycling in summer.', 3),
  ('guide', 'easy-family-bike-rides-calvia', 'Can children cycle in Calvia safely?', 'Yes, Calvia has several family-friendly cycling routes on quiet residential roads and coastal promenades. The Peguera to Camp de Mar route and Palma Nova promenade are particularly safe. Children under 16 must wear helmets by Spanish law. Avoid busy main roads and stick to recommended routes.', 1),
  ('guide', 'road-cycling-climbs-calvia', 'What gearing do I need for Galatzo climb?', 'For the Es Capdella to Galilea climb (8 km at average 5.5%, maximum 10%), a compact chainset with 34x28 is the absolute minimum. A 34x32 or sub-compact (30t inner ring) is recommended for most recreational riders. The final 2 km are the steepest and many riders wish they had lower gears.', 1),
  ('guide', 'road-cycling-climbs-calvia', 'How does cycling in Calvia compare to other Mallorca routes?', 'Calvia offers serious climbing that rivals the famous Tramuntana routes further north (Sa Calobra, Puig Major) while being more accessible. The Galatzo climb and Coll de sa Creu are challenging but shorter than the iconic northern passes. The advantage is less traffic and a year-round cycling community.', 2)
ON CONFLICT DO NOTHING;
