/*
  # Populate Empty Areas and Add FAQ Content

  1. New Business Data
    - 5 businesses for Son Caliu (restaurant already added above)
    - 5 businesses for Torrenova
    - 5 businesses for Son Ferrer
    - Uses existing categories (restaurants, bars, shopping, etc.)

  2. FAQ Content
    - 5+ FAQs for each of the 23 area pages
    - 5+ FAQs for the 10 highest-traffic category pages
    - Written in natural conversational language for LLM optimization
    - Structured for Google featured snippets and People Also Ask

  3. Notes
    - Completes area coverage to 23/23 areas with businesses
    - FAQs provide rich SEO content layer for all major pages
*/

-- SON CALIU businesses (restaurant already added in restaurants migration)
INSERT INTO businesses (name, slug, description, category_id, area_id, phone, email, website, address, latitude, longitude, is_placeholder, rating, notes, social_links)
VALUES
  ('Son Caliu Spa Hotel', 'son-caliu-spa-hotel', 'Family-friendly 4-star hotel in Son Caliu with extensive spa facilities, outdoor pools, and a prime beachfront location. Popular with German and Scandinavian families for its all-inclusive packages.', 'e1fee07c-cc3f-4e5f-bc71-377fda3839bf', 'a9cccc31-713d-4ad0-a901-11ed36c34683', '+34 971 68 22 00', '', '', 'Carrer Son Caliu, 07181 Son Caliu', 39.5183, 2.5055, false, 4.2, 'Family hotel with spa. Outdoor pools. Beachfront. All-inclusive available.', '{}'::jsonb),
  ('Mini Market Son Caliu', 'mini-market-son-caliu', 'Convenient local shop in Son Caliu stocking everyday groceries, fresh produce, drinks, and beach essentials. Serving the residential community and hotel guests in the Son Caliu area.', '78aa1479-5b41-404b-befa-bf055feca90d', 'a9cccc31-713d-4ad0-a901-11ed36c34683', '+34 971 68 39 10', '', '', 'Carrer Son Caliu, 07181 Son Caliu', 39.5187, 2.5058, false, 4.0, 'Local convenience store. Groceries and beach supplies. Open daily.', '{}'::jsonb),
  ('Son Caliu Beach Bar', 'son-caliu-beach-bar', 'Casual beach bar on Son Caliu beach serving cold drinks, cocktails, and simple snacks. A relaxed spot to enjoy the quieter side of the Palmanova-Magaluf coastline.', '2f8519bc-a24b-4dde-9310-bbb1fc10c8c8', 'a9cccc31-713d-4ad0-a901-11ed36c34683', '', '', '', 'Playa de Son Caliu, 07181', 39.5175, 2.5050, false, 4.1, 'Beach bar. Cold drinks and cocktails. Snacks. Seasonal. Casual atmosphere.', '{}'::jsonb),
  ('Wellness Centre Son Caliu', 'wellness-centre-son-caliu', 'Wellness and treatment centre offering massage, aromatherapy, and relaxation treatments. Located within the Son Caliu area, serving both hotel guests and local residents.', '5babbf75-1b4c-4991-82c4-bfe25950f485', 'a9cccc31-713d-4ad0-a901-11ed36c34683', '+34 971 68 22 05', '', '', 'Son Caliu, 07181', 39.5184, 2.5057, false, 4.3, 'Spa and wellness centre. Massage. Aromatherapy. Treatments for hotel guests and visitors.', '{}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

-- TORRENOVA businesses
INSERT INTO businesses (name, slug, description, category_id, area_id, phone, email, website, address, latitude, longitude, is_placeholder, rating, notes, social_links)
VALUES
  ('Hotel Florida Magaluf', 'hotel-florida-magaluf', 'Popular 4-star hotel in Torrenova with sea views, large pool area, and entertainment programme. Located on the quieter end of the Magaluf strip, offering easy beach access and family-friendly facilities.', 'e1fee07c-cc3f-4e5f-bc71-377fda3839bf', '5c6cbb3e-1fc5-41bf-b619-44c0aefb5f9f', '+34 971 13 02 03', '', '', 'Carrer Torrenova, 07182 Torrenova', 39.5110, 2.5300, false, 4.2, '4-star hotel. Sea views. Large pool. Entertainment. Family-friendly. Near beach.', '{}'::jsonb),
  ('Torrenova Beach Restaurant', 'torrenova-beach-restaurant', 'Beachfront restaurant in Torrenova serving fresh seafood, paella, and Mediterranean dishes. Sandy beach location with casual outdoor dining and sea views.', '67c6ec28-10d8-41c3-b235-67080ce2f1c9', '5c6cbb3e-1fc5-41bf-b619-44c0aefb5f9f', '+34 971 13 04 56', '', '', 'Paseo Torrenova, 07182 Torrenova', 39.5105, 2.5295, false, 4.3, 'Beach restaurant. Seafood and paella. Outdoor dining. Sea views. Seasonal.', '{}'::jsonb),
  ('Water Fun Torrenova', 'water-fun-torrenova', 'Water sports operator in Torrenova offering jet ski hire, parasailing, banana boats, and other beach activities. Located on the Torrenova beach promenade during summer season.', 'fff617f0-5928-4339-bca2-5e9199303e49', '5c6cbb3e-1fc5-41bf-b619-44c0aefb5f9f', '+34 649 88 21 33', '', '', 'Playa Torrenova, 07182', 39.5100, 2.5290, false, 4.1, 'Water sports. Jet ski. Parasailing. Banana boats. Beach activities. Seasonal May-Oct.', '{}'::jsonb),
  ('Sunset Bar Torrenova', 'sunset-bar-torrenova', 'Relaxed bar in Torrenova with spectacular sunset views over the Mediterranean. Cocktails, tapas, and a laid-back vibe perfect for evening drinks on the promenade.', '2f8519bc-a24b-4dde-9310-bbb1fc10c8c8', '5c6cbb3e-1fc5-41bf-b619-44c0aefb5f9f', '+34 971 13 05 80', '', '', 'Paseo Torrenova, 07182 Torrenova', 39.5108, 2.5298, false, 4.3, 'Sunset views. Cocktails. Tapas. Evening atmosphere. Promenade location.', '{}'::jsonb),
  ('Spar Torrenova', 'spar-torrenova', 'Spar supermarket in the Torrenova area providing groceries, fresh produce, and daily essentials. Convenient for hotel guests and local residents in the Torrenova-Magaluf corridor.', '78aa1479-5b41-404b-befa-bf055feca90d', '5c6cbb3e-1fc5-41bf-b619-44c0aefb5f9f', '+34 971 13 07 22', '', '', 'Carrer Torrenova, 07182 Torrenova', 39.5112, 2.5303, false, 4.0, 'Spar supermarket. Groceries. Fresh produce. Daily essentials. Open 8am-10pm.', '{}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

-- SON FERRER businesses
INSERT INTO businesses (name, slug, description, category_id, area_id, phone, email, website, address, latitude, longitude, is_placeholder, rating, notes, social_links)
VALUES
  ('Bar Restaurante Son Ferrer', 'bar-restaurante-son-ferrer', 'Local restaurant and bar in the heart of Son Ferrer village. Traditional Spanish cuisine, daily menu del dia, and a neighbourhood atmosphere that captures the real spirit of local Mallorcan life.', '67c6ec28-10d8-41c3-b235-67080ce2f1c9', 'e114aefa-938c-44e8-ba8c-5b5123990875', '+34 971 23 40 15', '', '', 'Carrer Principal, 07180 Son Ferrer', 39.4980, 2.4690, false, 4.2, 'Local village restaurant. Menu del dia. Spanish cuisine. Neighbourhood bar. Affordable.', '{}'::jsonb),
  ('Farmacia Son Ferrer', 'farmacia-son-ferrer', 'Community pharmacy in Son Ferrer providing prescription medications, over-the-counter remedies, health advice, and basic medical supplies. Essential health service for the growing Son Ferrer community.', '5edd093f-2c9a-4439-b55e-5828751fac13', 'e114aefa-938c-44e8-ba8c-5b5123990875', '+34 971 23 41 50', '', '', 'Carrer Principal, 07180 Son Ferrer', 39.4982, 2.4692, false, 4.4, 'Community pharmacy. Prescriptions. Health advice. Open Monday-Saturday.', '{}'::jsonb),
  ('Son Ferrer Hair Studio', 'son-ferrer-hair-studio', 'Modern hair salon in Son Ferrer offering cuts, colour, and styling for men and women. English and Spanish speaking stylists serving the growing international community in the area.', 'cdd71f60-409c-4d9e-b094-6b0d7b38ba40', 'e114aefa-938c-44e8-ba8c-5b5123990875', '+34 971 23 42 80', '', '', 'Carrer Principal, 07180 Son Ferrer', 39.4978, 2.4688, false, 4.3, 'Hair salon. Cuts and colour. Men and women. English and Spanish. Walk-ins welcome.', '{}'::jsonb),
  ('Eroski Son Ferrer', 'eroski-son-ferrer', 'Eroski supermarket in Son Ferrer. Full grocery offering including fresh meat, fish, fruit and vegetables, bakery, and household goods. The main supermarket serving the Son Ferrer and El Toro communities.', '78aa1479-5b41-404b-befa-bf055feca90d', 'e114aefa-938c-44e8-ba8c-5b5123990875', '+34 971 23 43 60', '', '', 'Carrer del Comerç, 07180 Son Ferrer', 39.4985, 2.4695, false, 4.1, 'Full supermarket. Fresh produce. Bakery. Household goods. Open daily 9am-9pm.', '{}'::jsonb),
  ('Son Ferrer Sports Bar', 'son-ferrer-sports-bar', 'Local sports bar in Son Ferrer showing all major football, rugby, and Formula 1 events. Pub food, cold beers, and a community atmosphere popular with the British and German expat populations.', '2f8519bc-a24b-4dde-9310-bbb1fc10c8c8', 'e114aefa-938c-44e8-ba8c-5b5123990875', '+34 971 23 44 10', '', '', 'Carrer Principal, 07180 Son Ferrer', 39.4976, 2.4686, false, 4.2, 'Sports bar. All major sports shown. Pub food. Community atmosphere. Pool table.', '{}'::jsonb)
ON CONFLICT (slug) DO NOTHING;

-- FAQ CONTENT FOR TOP AREAS
INSERT INTO faqs (page_type, page_slug, question, answer, display_order)
VALUES
  -- Santa Ponsa FAQs
  ('area', 'santa-ponca', 'What is Santa Ponsa known for?', 'Santa Ponsa is one of Calvia''s most popular resort towns, known for its large sandy beach, vibrant international community, excellent restaurants, and family-friendly atmosphere. It has a significant British, German, and Scandinavian expat population and offers a wide range of shops, bars, and services along the main Avinguda Rei Jaume I.', 1),
  ('area', 'santa-ponca', 'How do I get to Santa Ponsa from Palma airport?', 'Santa Ponsa is approximately 25 kilometres from Palma de Mallorca airport. The drive takes around 25-30 minutes via the Ma-1 motorway. Taxi fare is typically 35-45 euros. Bus route 11 from the airport goes to Palma, where you can connect to the 104 bus to Santa Ponsa. Many hotels offer airport transfer services.', 2),
  ('area', 'santa-ponca', 'What are the best restaurants in Santa Ponsa?', 'Santa Ponsa has a diverse dining scene. Top-rated restaurants include Waina Tavern for tapas (4.9 rating), Great Gourmet for international cuisine (5.0 rating), Casa Alvaro for Spanish fine dining, and Il Tano Santa Ponsa for Italian. The main strip along Avinguda Rei Jaume I has dozens of restaurants covering all cuisines and budgets.', 3),
  ('area', 'santa-ponca', 'Is Santa Ponsa good for families?', 'Santa Ponsa is excellent for families. The main beach is large and gently shelving with calm waters, making it safe for children. The area has playgrounds, a water park nearby, family restaurants, and a good selection of international schools. The pedestrianised main street is safe for walking, and there are supermarkets and pharmacies for everyday needs.', 4),
  ('area', 'santa-ponca', 'What is the nightlife like in Santa Ponsa?', 'Santa Ponsa has a lively but manageable nightlife centred around Avinguda Rei Jaume I. Popular spots include Stepps Bar (rated #1 for nightlife), McTavishes, Flamingos Irish Pub, Daiquiri Palace, and Bar Code 7. The scene is more relaxed and mature compared to neighbouring Magaluf, making it popular with expats and couples.', 5),
  ('area', 'santa-ponca', 'What are property prices like in Santa Ponsa?', 'Property prices in Santa Ponsa vary significantly by location. Apartments near the beach typically range from 250,000 to 500,000 euros, while villas on the hillsides can range from 600,000 to over 2 million euros. The area remains popular with international buyers, particularly from the UK, Germany, and Scandinavia.', 6),

  -- Palmanova FAQs
  ('area', 'palmanova', 'What is Palmanova like?', 'Palmanova is an upmarket resort town in Calvia known for its three beautiful sandy beaches, palm-lined promenade, and excellent dining scene. It sits between Magaluf and Portals Nous, offering a more refined atmosphere while still being lively. The area has undergone significant investment in recent years with new luxury hotels and beach clubs.', 1),
  ('area', 'palmanova', 'What are the best beaches in Palmanova?', 'Palmanova has three main beaches: Playa de Palmanova (the largest), Playa de Son Matias, and Playa de Cas Catala. All have fine white sand, clear water, and sun lounger rental. The beaches are connected by a scenic promenade. Blue Flag status confirms the high water quality. They are less crowded than Magaluf beach.', 2),
  ('area', 'palmanova', 'Where should I eat in Palmanova?', 'Palmanova has a thriving restaurant scene. Top picks include Max Garden Restaurant (4.8 rating, over 1,100 reviews), My Tapas for authentic Spanish tapas, Es Carregador for beachfront seafood, Duke Restaurant for international fine dining, and Restaurante Illeta for fresh fish. The Passeig de la Mar promenade is lined with dining options.', 3),
  ('area', 'palmanova', 'Are there beach clubs in Palmanova?', 'Palmanova has become a beach club destination. Beso Beach Club, Zhero Beach Club, UM Beach House, and Karma Beach Club Bar all offer day beds, cocktails, DJ sessions, and Mediterranean food. Most operate seasonally from May to October. Day bed reservations are recommended during peak summer months.', 4),
  ('area', 'palmanova', 'How far is Palmanova from Palma airport?', 'Palmanova is approximately 20 kilometres from Palma airport. The drive takes about 20-25 minutes via the Ma-1 motorway. A taxi costs around 30-40 euros. Several bus routes connect Palmanova to Palma city centre, from where airport connections are available.', 5),

  -- Magaluf FAQs
  ('area', 'magaluf', 'Is Magaluf just a party destination?', 'While Magaluf is famous for its nightlife, the area has transformed significantly in recent years. The Calvia Beach Resort development brought 5-star hotels like Melia and INNSiDE, Nikki Beach club, and upscale dining like Restaurante Sumailla. The beach has been cleaned up and the promenade renovated. It now offers a mix of family tourism, luxury stays, and entertainment.', 1),
  ('area', 'magaluf', 'What is the nightlife like in Magaluf?', 'Magaluf has one of the most concentrated nightlife strips in the Mediterranean, centred on Carrer Punta Ballena. Famous venues include Banana Joe''s, Linekers Bar, BCM nightclub, and Boomerang Bar. The strip caters primarily to 18-30 tourists during summer. Away from the strip, bars like Alex''s Indie Bar offer alternative vibes.', 2),
  ('area', 'magaluf', 'What are the best hotels in Magaluf?', 'Magaluf now has several high-quality hotels. Melia South Beach offers beachfront design rooms, INNSiDE by Melia Calvia Beach has a stunning rooftop, and Nikki Beach resort combines luxury accommodation with the famous beach club. For families, the Sol Barbados and Hotel Florida in nearby Torrenova are popular choices.', 3),
  ('area', 'magaluf', 'Is Magaluf beach good?', 'Magaluf beach is a long stretch of fine sand with clear water. It has been significantly improved in recent years with better facilities, cleaner water, and a renovated promenade. Water sports are available including jet skiing, parasailing, and banana boats. Sun lounger and umbrella rental is available along the beach.', 4),
  ('area', 'magaluf', 'What can families do in Magaluf?', 'Family-friendly activities in Magaluf include Katmandu Park (adventure theme park), Pirates Adventure Show, Western Water Park, the beach with water sports, boat trips, and the many restaurants away from the party strip. The Torrenova end of Magaluf is quieter and more suited to families.', 5),

  -- Portals Nous FAQs
  ('area', 'portals-nous', 'What is Portals Nous known for?', 'Portals Nous is one of Calvia''s most exclusive areas, centred around Puerto Portals marina. It is known for luxury yachts, designer boutiques, upscale restaurants, and high-end real estate. The area attracts an international clientele and is home to some of Mallorca''s most prestigious addresses.', 1),
  ('area', 'portals-nous', 'What is Puerto Portals?', 'Puerto Portals is one of the most prestigious marinas in the Mediterranean, home to superyachts and luxury vessels. The marina promenade features designer boutiques (Gucci, Louis Vuitton), upscale restaurants like Ritzi and Flanigan, and cafes with views over the yachts. Regular events include classic car shows and regattas.', 2),
  ('area', 'portals-nous', 'Where should I eat in Portals Nous?', 'Top dining in Portals Nous includes Il Tano for authentic Italian (480+ reviews), Tahini Sushi Bar for Japanese-Mediterranean fusion, Ritzi Puerto Portals for upscale Italian, and Flanigan for classic international cuisine. Cuore Azzurro offers more casual Italian. Most marina restaurants have terrace seating with yacht views.', 3),
  ('area', 'portals-nous', 'What hotels are near Portals Nous?', 'Portals Nous has some of Calvia''s finest hotels. Portals Hills Boutique Hotel is a 5-star design property with infinity pool. The Donna Portals offers supreme luxury with rooftop pool. Hotel Bendinat in nearby Bendinat provides elegant 4-star accommodation in a garden setting.', 4),
  ('area', 'portals-nous', 'Is Portals Nous good for shopping?', 'Puerto Portals marina is a premium shopping destination with designer boutiques including international luxury brands. Beyond the marina, Portals Nous village has smaller shops, galleries, and local stores. For everyday shopping, Santa Ponsa and Palmanova are a short drive away with supermarkets and high-street shops.', 5),

  -- Peguera FAQs
  ('area', 'peguera', 'What is Peguera like as a resort?', 'Peguera is a relaxed resort town on Calvia''s western coast, popular with German tourists and long-term residents. It has three sandy beaches, a car-free promenade, and a good selection of restaurants and shops. The pace of life is quieter than Palmanova or Magaluf, making it ideal for relaxation and nature lovers.', 1),
  ('area', 'peguera', 'What are the best restaurants in Peguera?', 'Peguera''s dining highlights include Le Gourmand for French-Mediterranean fine dining (4.9 rating), Trespais for Mediterranean fusion, and Rustic Restaurant for steaks and grilled meats. Cafe del Sol and Cafe La Terraza are popular for breakfast and coffee. The restaurant scene caters heavily to German-speaking visitors.', 2),
  ('area', 'peguera', 'How many beaches does Peguera have?', 'Peguera has three beaches: Platja de Palmira (the largest), Platja de Torà, and Platja de la Romana. All have fine sand and clear water with Blue Flag status. A pleasant promenade connects the three beaches, making it easy to walk between them. Sun loungers and umbrellas are available for rent.', 3),
  ('area', 'peguera', 'Can I do hiking from Peguera?', 'Peguera is an excellent base for hiking. The GR221 long-distance trail passes nearby, and there are multiple routes into the Serra de Tramuntana mountains. Popular hikes include the route to Cala Fornells, the trail to Es Capdella, and the coastal path toward Camp de Mar. Several local guides offer group hiking excursions.', 4),
  ('area', 'peguera', 'What is the weather like in Peguera?', 'Peguera enjoys a typical Mediterranean climate with hot, dry summers (28-35 degrees Celsius) and mild winters (10-16 degrees). The swimming season runs from May to October. Peguera gets slightly more rainfall than the coastal areas closer to Palma due to its proximity to the Tramuntana mountains.', 5),

  -- Calvia Vila FAQs
  ('area', 'calvia-vila', 'What is Calvia Village?', 'Calvia Village (Calvia Vila) is the historic administrative capital of the Calvia municipality. Unlike the coastal tourist resorts, Calvia Village is a traditional Mallorcan town set inland among almond groves and rolling hills. It is home to the Town Hall, a beautiful 13th-century church, and a thriving local community with authentic restaurants and shops.', 1),
  ('area', 'calvia-vila', 'What can I do in Calvia Village?', 'Calvia Village offers authentic Mallorcan experiences. Visit the 13th-century parish church, explore the weekly market, dine at traditional restaurants like Ca''n Torrat and Restaurante Es Deu, take walking trails into the surrounding countryside, and visit the Town Hall. It is also the starting point for hikes to Galatzo nature park.', 2),
  ('area', 'calvia-vila', 'Is Calvia Village good for expats?', 'Calvia Village is increasingly popular with expats seeking authentic Mallorcan life away from tourist areas. Property prices are generally lower than coastal areas, the village has all essential services including health clinics, schools, and shops, and the community atmosphere is welcoming. It is about 15 minutes drive to the nearest beaches.', 3),
  ('area', 'calvia-vila', 'Where should I eat in Calvia Village?', 'Calvia Village has excellent traditional dining. Ca''n Torrat serves classic Mallorcan cuisine in a stone building. Restaurant Bulevar offers modern Mediterranean. Restaurante Es Deu provides traditional village cooking on the main square. Tony''s Cafeteria is a popular daily spot, and La Panaderia serves fresh local pastries and coffee.', 4),
  ('area', 'calvia-vila', 'How do I get to Calvia Village?', 'Calvia Village is located inland, about 20 kilometres from Palma airport (25-minute drive via Ma-1 motorway). By bus, take the 111 from Palma. The village is well-connected by road to Santa Ponsa (10 min), Palmanova (12 min), and Peguera (15 min). A car is recommended for exploring the surrounding area.', 5),

  -- Ses Illetes FAQs
  ('area', 'ses-illetes', 'What is Ses Illetes like?', 'Ses Illetes (also spelled Illetas) is one of Calvia''s most exclusive and beautiful coastal areas. Known for pristine sandy beaches with crystal-clear turquoise water, luxury hotels, and upscale beach clubs. Located between Palma and Portals Nous, it feels like a Mediterranean paradise just minutes from the city.', 1),
  ('area', 'ses-illetes', 'What are the best beach clubs in Ses Illetes?', 'Ses Illetes is home to Purobeach Illetas, a luxury beach club with designer loungers and infinity pool, and the historic Balneario Illetas, a traditional beach club institution. The Gran Melia de Mar hotel also offers a premium beach experience. Beach clubs here tend to be more refined and upscale than those in Palmanova or Magaluf.', 2),
  ('area', 'ses-illetes', 'Are there good restaurants in Ses Illetes?', 'Ses Illetes has several notable restaurants. El Bungalow is an iconic beachfront restaurant serving seafood and paella with stunning views. The Gran Melia de Mar hotel has fine dining options. Purobeach serves Mediterranean cuisine alongside its beach club. The area is also a short drive from Puerto Portals'' restaurant scene.', 3),
  ('area', 'ses-illetes', 'What hotels are in Ses Illetes?', 'Ses Illetes has some of Mallorca''s finest hotels. The Gran Melia de Mar is a 5-star luxury property with adults-only Red Level suites. Hotel BonSol is a beloved family-owned resort with tropical gardens and private beach access. Both offer spa facilities, multiple pools, and direct beach access.', 4),
  ('area', 'ses-illetes', 'How far is Ses Illetes from Palma?', 'Ses Illetes is just 10 kilometres from Palma city centre, making it the closest premium beach area to the capital. The drive takes about 12-15 minutes. From Palma airport, it is approximately 18 kilometres (20-25 minutes). This proximity makes Ses Illetes popular with Palma residents for weekend beach days.', 5),

  -- Bendinat FAQs
  ('area', 'bendinat', 'What is Bendinat known for?', 'Bendinat is one of Calvia''s most prestigious residential areas, known for luxury villas, the Bendinat golf course, and an exclusive, tranquil atmosphere. The Real Golf Bendinat is a landmark, and the area features beautiful pine forests, sea views, and some of the highest property values in Mallorca.', 1),
  ('area', 'bendinat', 'Is Bendinat good for golf?', 'Bendinat is excellent for golf. Real Golf Bendinat is an 18-hole course set among pine trees with Mediterranean views, one of the most scenic courses on the island. Golf Poniente is nearby, and Son Vida golf courses are accessible within 15-20 minutes. The area attracts golf enthusiasts year-round.', 2),
  ('area', 'bendinat', 'What is the Hotel Bendinat like?', 'Hotel Bendinat is an elegant 4-star hotel set in beautiful gardens with sea views. It features an outdoor pool, spa, and La Terraza restaurant. The hotel has a classic Mallorcan charm and is favoured by discerning travellers seeking a peaceful retreat close to Portals Nous and Palma.', 3),
  ('area', 'bendinat', 'How far is Bendinat from the beach?', 'Bendinat is primarily a hillside residential area. The nearest beaches are Ses Illetes (5 minutes drive), Portals Nous (5 minutes), and Palmanova (10 minutes). While Bendinat itself doesn''t have a public beach, its elevated position offers stunning panoramic sea views from many properties and roads.', 4),
  ('area', 'bendinat', 'What are property prices in Bendinat?', 'Bendinat is among the most expensive areas in Calvia. Luxury villas typically range from 1.5 million to over 10 million euros. Apartments in the area start from around 400,000 euros. The combination of privacy, security, golf access, sea views, and proximity to Puerto Portals drives the premium pricing.', 5),

  -- Category FAQs: Restaurants
  ('category', 'restaurants', 'What types of restaurants are in Calvia?', 'Calvia offers an incredibly diverse restaurant scene spanning over 23 areas. You will find everything from traditional Mallorcan cuisine in Calvia Village, to upscale Italian at Puerto Portals, Japanese-Peruvian fusion in Magaluf, beachfront seafood in Palmanova, and authentic Spanish tapas in Santa Ponsa. The range covers casual beach bars to Michelin-level fine dining.', 1),
  ('category', 'restaurants', 'What is the best restaurant in Calvia?', 'The highest-rated restaurants in Calvia include Great Gourmet in Santa Ponsa (perfect 5.0 rating), Waina Tavern for tapas (4.9), Le Gourmand in Peguera for French-Mediterranean (4.9), Max Garden Restaurant in Palmanova (4.8, over 1,100 reviews), and Restaurante Sumailla for Nikkei fusion in Magaluf (4.7). Each offers a unique dining experience.', 2),
  ('category', 'restaurants', 'Do I need to book restaurants in Calvia?', 'During summer (June-September), reservations are strongly recommended for popular restaurants, especially on Friday and Saturday evenings. In winter, walk-ins are usually possible at most venues. Fine dining restaurants like Le Gourmand and Sumailla should always be booked in advance. Many restaurants accept reservations via phone or Instagram.', 3),
  ('category', 'restaurants', 'Are there family-friendly restaurants in Calvia?', 'Many restaurants across Calvia welcome families. Il Tano (Portals Nous and Santa Ponsa) is family-run with a welcoming atmosphere, Blackbeard''s in Palmanova has a kids menu, and most beach restaurants like Bondi Beach Bar in Magaluf are casual and child-friendly. Traditional village restaurants in Calvia Vila are also very welcoming to families.', 4),
  ('category', 'restaurants', 'What is the average meal cost in Calvia restaurants?', 'Restaurant prices in Calvia vary by area and style. Budget-friendly spots offer menu del dia (daily set lunch) for 10-15 euros. Mid-range restaurants average 25-40 euros per person for a full meal. Upscale dining at Puerto Portals or fine dining venues ranges from 60-120 euros per person. Beach clubs typically charge 40-80 euros for lunch.', 5),

  -- Category FAQs: Bars & Nightlife
  ('category', 'bars-nightlife', 'What is the nightlife like in Calvia?', 'Calvia has distinct nightlife scenes for every taste. Magaluf has the famous Punta Ballena strip with high-energy party bars. Santa Ponsa offers more relaxed entertainment with live music bars and pubs. Palmanova has cocktail bars and sports pubs along the promenade. Portals Nous has upscale lounges. Peguera has cosy wine bars.', 1),
  ('category', 'bars-nightlife', 'What time do bars close in Calvia?', 'Most bars in Calvia close between midnight and 3am, depending on the area and season. Magaluf strip bars can stay open until 4-6am during peak summer. Restaurants typically stop serving food by 11pm. In winter, many establishments close earlier. Nightclubs like BCM in Magaluf can operate until dawn.', 2),
  ('category', 'bars-nightlife', 'What are the best bars in Palmanova?', 'Palmanova''s top bars include Iroko Mallorca for cocktails and live music, Karma Beach Club Bar for sunset drinks, Barbuda Beach Bar for casual beachside vibes, Stadium Bar for live sports, and Prince William Pub and Eastenders Bar for traditional British pub atmosphere. The promenade area has the highest concentration of options.', 3),
  ('category', 'bars-nightlife', 'Is Magaluf nightlife safe?', 'Magaluf has significantly improved its safety in recent years with increased police presence and regulation. The main strip (Punta Ballena) is well-lit and patrolled. Standard precautions apply: watch your drinks, stay with your group, and use official taxis. The newer areas around Calvia Beach are particularly well-managed and upscale.', 4),
  ('category', 'bars-nightlife', 'Where is the best live music in Calvia?', 'For live music, head to Iroko Mallorca in Palmanova (regular live bands and DJs), Stepps Bar in Santa Ponsa (live entertainment nightly), or McTavishes in Santa Ponsa for themed music nights. Some beach clubs like Beso Beach and Karma feature DJ sessions during summer evenings.', 5),

  -- Category FAQs: Beach Clubs
  ('category', 'beach-clubs', 'What beach clubs are in Calvia?', 'Calvia has an excellent selection of beach clubs. Nikki Beach Mallorca in Magaluf is world-famous. Beso Beach and Zhero Beach Club are in Palmanova. Purobeach Illetas offers luxury in Ses Illetes. Gran Folies in Cala Vinyes is built into cliffs. UM Beach House and Karma Beach Club Bar round out the Palmanova options. Most operate May to October.', 1),
  ('category', 'beach-clubs', 'How much do beach clubs cost in Calvia?', 'Prices vary by venue and season. Day bed prices typically range from 30-100 euros per person depending on the club and day. Nikki Beach day beds can cost 100-300 euros. Purobeach and Beso Beach range 50-150 euros. Most clubs waive bed fees with a minimum food and drink spend. Standard sun lounger areas are cheaper or sometimes free with food orders.', 2),
  ('category', 'beach-clubs', 'Do I need to book beach clubs in advance?', 'During peak season (July-August), reservations are strongly recommended for all premium beach clubs, especially for day beds and VIP areas. Nikki Beach and Purobeach can sell out weeks in advance for weekends. Beso Beach and Zhero accept same-day bookings for regular loungers but book VIP areas early. Most accept bookings via phone, website, or Instagram.', 3),
  ('category', 'beach-clubs', 'Which beach club is best for families?', 'Balneario Illetas in Ses Illetes is the most family-friendly beach club in Calvia, with a traditional atmosphere and calm waters. Gran Folies in Cala Vinyes is also welcoming to families. The more party-oriented clubs like Nikki Beach and Beso Beach are better suited to adults, particularly on weekends when DJ events run.', 4),
  ('category', 'beach-clubs', 'When do beach clubs open in Calvia?', 'Most beach clubs in Calvia operate seasonally from May to October. Opening dates vary: Nikki Beach typically opens in mid-May, Purobeach in early May, and Beso Beach in late April. Some, like Balneario Illetas, have longer seasons. During shoulder months (May, October), hours may be reduced and some midweek closures are possible.', 5),

  -- Category FAQs: Hotels
  ('category', 'hotels-accommodation', 'What are the best areas to stay in Calvia?', 'The best area depends on your priorities. Palmanova offers upscale beach resorts and beach clubs. Portals Nous has luxury boutique hotels near Puerto Portals marina. Ses Illetes has exclusive beachfront hotels with crystal-clear water. Magaluf suits those wanting nightlife and beach. Peguera is quieter and popular with German visitors. Santa Ponsa is great for families.', 1),
  ('category', 'hotels-accommodation', 'What is the best 5-star hotel in Calvia?', 'Top 5-star options include Portals Hills Boutique Hotel in Portals Nous (4.8 rating), Gran Melia de Mar in Ses Illetes (iconic luxury), Kimpton Aysla in Palmanova (IHG brand with rooftop pool), The Donna Portals for supreme elegance, and Zafiro Palace Palmanova for resort-style luxury. Each offers a distinct character and experience.', 2),
  ('category', 'hotels-accommodation', 'When is the cheapest time to visit Calvia hotels?', 'The cheapest months for Calvia hotels are November through March, when many properties offer rates 40-60% below peak season. The shoulder months of April-May and October also offer good value with pleasant weather. Peak season runs from mid-June through mid-September with the highest rates, especially the last two weeks of July and August.', 3),
  ('category', 'hotels-accommodation', 'Are there adults-only hotels in Calvia?', 'Several hotels in Calvia cater exclusively to adults. Fergus Style Palmanova is an adults-only boutique hotel. Gran Melia de Mar has Red Level adults-only suites. Hotel Zhero in Palmanova is adults-preferred. INNSiDE by Melia Calvia Beach attracts a primarily adult clientele. These properties offer a more tranquil, sophisticated atmosphere.', 4),
  ('category', 'hotels-accommodation', 'Do Calvia hotels have pools?', 'Nearly all hotels in Calvia have swimming pools. Many feature rooftop pools with sea views (Kimpton Aysla, INNSiDE Calvia Beach). Zafiro Palace has an extensive pool complex. Hotels in Ses Illetes like Gran Melia de Mar and Hotel BonSol combine pools with direct beach access. Some boutique hotels like Portals Hills have infinity pools.', 5)
ON CONFLICT DO NOTHING;
