/*
  # Seed FAQs for guides missing them - Batch 1

  1. Changes
    - Adds 3 FAQs each for 13 guides that currently have zero FAQ entries
    - Covers: Pilates/Yoga, Nightlife, Water Sports, Financial Planning,
      Palmanova Restaurants, Beach Clubs, Real Estate, Boat Charters,
      Santa Ponsa Restaurants, Tennis Clubs, Professional Services,
      Yachting, Family Activities

  2. Impact
    - Guide detail pages will now display FAQ sections instead of being empty
    - Improves SEO with structured Q&A content
*/

INSERT INTO faqs (page_type, page_slug, question, answer, display_order) VALUES
('guide', 'best-pilates-yoga-studios-calvia', 'What styles of yoga and pilates are available in Calvia?', 'Studios in Calvia offer a wide range of styles including Hatha, Vinyasa, Ashtanga, and Yin yoga, as well as mat Pilates, reformer Pilates, and fusion classes. Many studios also offer outdoor sessions on the beach or in gardens during warmer months.', 1),
('guide', 'best-pilates-yoga-studios-calvia', 'Do I need to be experienced to join a class?', 'Not at all. Most studios in Calvia welcome all levels from complete beginners to advanced practitioners. Classes are typically labelled by difficulty level and instructors provide modifications so everyone can participate safely.', 2),
('guide', 'best-pilates-yoga-studios-calvia', 'How much do yoga and pilates classes cost in Calvia?', 'Drop-in classes typically range from 12 to 20 euros. Most studios offer multi-class packs or monthly memberships that bring the per-class cost down significantly. Some also offer free trial classes for newcomers.', 3),

('guide', 'nightlife-guide-magaluf', 'Is Magaluf nightlife only for young party crowds?', 'While Magaluf is famous for its lively club scene, the area has evolved considerably. You will find sophisticated cocktail bars, live music venues, beach clubs, and relaxed wine bars alongside the more energetic clubs, catering to all ages and tastes.', 1),
('guide', 'nightlife-guide-magaluf', 'What are the best months for nightlife in Magaluf?', 'The peak nightlife season runs from May through September, with July and August being the busiest. Many venues open earlier and close later during these months. Some bars and restaurants operate year-round with a more relaxed atmosphere in winter.', 2),
('guide', 'nightlife-guide-magaluf', 'Is it safe to go out at night in Magaluf?', 'Magaluf is generally safe for nightlife. The area has increased security presence during summer, and most venues have their own security staff. Standard precautions apply: stay aware of your surroundings, watch your belongings, and stick to well-lit areas.', 3),

('guide', 'water-sports-diving-calvia', 'What water sports can I try in Calvia?', 'Calvia offers an impressive range of water sports including paddleboarding, kayaking, jet skiing, parasailing, wakeboarding, windsurfing, snorkelling, and scuba diving. The calm Mediterranean waters make it ideal for both beginners and experienced water sports enthusiasts.', 1),
('guide', 'water-sports-diving-calvia', 'Do I need certification for scuba diving in Calvia?', 'For introductory dives (baptizo or discover scuba), no certification is needed. For independent diving, a PADI Open Water or equivalent certification is required. Several dive centres in Calvia offer certification courses ranging from beginner to advanced levels.', 2),
('guide', 'water-sports-diving-calvia', 'When is the best season for water sports?', 'The water sports season runs from April to October, with the warmest water temperatures (24-27 degrees) from June through September. Diving visibility is generally best from May to July. Some operators run year-round for activities like kayaking and paddleboarding.', 3),

('guide', 'financial-planning-mallorca-guide', 'Do I need a financial advisor if I move to Mallorca?', 'It is highly recommended. Tax obligations for residents in Spain differ significantly from other countries, and there are specific rules for expats regarding worldwide income, wealth tax, and reporting foreign assets. A qualified advisor helps you stay compliant and optimize your finances.', 1),
('guide', 'financial-planning-mallorca-guide', 'What taxes should expats be aware of in Mallorca?', 'Key taxes include Spanish income tax (IRPF), wealth tax, capital gains tax, and the Modelo 720 foreign asset reporting requirement. Property owners also face IBI (property tax) and, if renting out, rental income tax. Double taxation treaties may apply depending on your home country.', 2),
('guide', 'financial-planning-mallorca-guide', 'Can I keep my investments in my home country?', 'Yes, but you must declare worldwide assets and income to Spanish tax authorities. Some investment structures may be tax-inefficient under Spanish rules. A cross-border financial advisor can help restructure your portfolio to work within the Spanish tax system.', 3),

('guide', 'best-restaurants-palmanova', 'What type of cuisine is most popular in Palmanova?', 'Palmanova offers a diverse dining scene with Mediterranean and Spanish cuisine leading the way. You will also find excellent Italian, Asian, and international restaurants. Seafood is a particular highlight given the coastal location, with many restaurants serving fresh catches daily.', 1),
('guide', 'best-restaurants-palmanova', 'Are restaurants in Palmanova expensive?', 'Palmanova caters to a range of budgets. You can find excellent tapas and menu del dia options from 10-15 euros, mid-range dining from 20-40 euros per person, and upscale restaurants from 50 euros and above. Lunch menus typically offer the best value.', 2),
('guide', 'best-restaurants-palmanova', 'Do I need to book restaurants in advance in Palmanova?', 'During peak summer months (July and August), booking is strongly recommended for popular restaurants, especially for dinner. Outside of peak season, walk-ins are usually fine, though weekend evenings can still be busy. Most restaurants accept bookings by phone or online.', 3),

('guide', 'best-beach-clubs-calvia', 'What is the typical cost of a day at a beach club in Calvia?', 'Sunbed and umbrella packages typically start from 20-40 euros per person, with premium beachfront beds ranging from 50 to 150 euros. Many clubs operate a minimum spend policy rather than an entry fee. Food and drinks are priced at a premium compared to regular restaurants.', 1),
('guide', 'best-beach-clubs-calvia', 'Do beach clubs in Calvia require reservations?', 'During summer weekends and holidays, reservations are strongly recommended and often essential for popular venues. Weekdays are more relaxed, especially early in the season. Most clubs allow online booking or reservations via phone or social media.', 2),
('guide', 'best-beach-clubs-calvia', 'Are beach clubs in Calvia open year-round?', 'Most beach clubs operate seasonally from May through October, with some opening as early as April and closing in November. A few venues in popular areas like Palmanova and Puerto Portals remain open year-round with a more relaxed winter schedule.', 3),

('guide', 'real-estate-guide-calvia', 'What is the average property price in Calvia?', 'Prices vary significantly by area. Apartments typically start from around 250,000 euros in areas like Magaluf and Son Ferrer, while properties in premium locations like Portals Nous, Bendinat, and Sol de Mallorca can range from 1 to 10 million euros or more. Villas with sea views command the highest prices.', 1),
('guide', 'real-estate-guide-calvia', 'What additional costs should I expect when buying property?', 'Budget for approximately 10-13 percent on top of the purchase price. This covers transfer tax (ITP) at 8-13 percent, notary fees, property registry fees, legal fees (typically 1-1.5 percent), and mortgage arrangement fees if applicable. A gestor or lawyer will guide you through the process.', 2),
('guide', 'real-estate-guide-calvia', 'Can non-residents buy property in Calvia?', 'Yes, there are no restrictions on foreign nationals buying property in Spain. You will need a NIE (foreigner identification number), a Spanish bank account, and a good lawyer familiar with Spanish property law. The process typically takes 1-3 months from offer to completion.', 3),

('guide', 'boat-charters-calvia-guide', 'Do I need a boating license to rent a boat in Calvia?', 'For boats under 6 metres and up to 15 HP, no license is required. For larger vessels, you need a valid boating license. Many charter companies offer skippered rentals where an experienced captain is included, which is popular for day trips and special occasions.', 1),
('guide', 'boat-charters-calvia-guide', 'What is the best time of year for boat charters?', 'The prime season is June through September with calm seas and warm weather. May and October offer excellent conditions with fewer crowds and lower prices. Some operators offer winter charters on calm days, which are ideal for whale watching and quieter coastal explorations.', 2),
('guide', 'boat-charters-calvia-guide', 'How much does a boat charter cost in Calvia?', 'Small motorboat rentals (no license required) start from about 150-250 euros for a half day. Mid-size boats with skipper range from 400-800 euros per day. Luxury yacht charters start from around 1,500 euros per day and can go well above 5,000 euros depending on the vessel size and season.', 3),

('guide', 'best-restaurants-santa-ponsa', 'What makes Santa Ponsa a good dining destination?', 'Santa Ponsa combines a relaxed beach town atmosphere with a surprisingly sophisticated food scene. The area attracts quality chefs who serve everything from traditional Mallorcan dishes to international fusion cuisine, all within walking distance of the beautiful bay.', 1),
('guide', 'best-restaurants-santa-ponsa', 'Are there good vegetarian and vegan options in Santa Ponsa?', 'Yes, the dining scene has evolved to accommodate plant-based diets. Most restaurants offer vegetarian options, and several specialize in vegan and health-conscious cuisine. Mediterranean cooking naturally lends itself to excellent vegetable-based dishes.', 2),
('guide', 'best-restaurants-santa-ponsa', 'Is parking easy near Santa Ponsa restaurants?', 'Street parking is available but can be competitive during summer evenings. Many restaurants along the boulevard have nearby public parking areas. Consider walking if you are staying locally, or arrive before 8 PM for the best parking options during peak season.', 3),

('guide', 'best-tennis-clubs-calvia', 'What level do I need to be to join a tennis club in Calvia?', 'Tennis clubs in Calvia welcome players of all levels, from complete beginners to competitive players. Most clubs offer group lessons organized by ability level, as well as private coaching for faster improvement. Social play sessions are a great way to meet other players.', 1),
('guide', 'best-tennis-clubs-calvia', 'How much does tennis club membership cost?', 'Annual memberships typically range from 300 to 1,200 euros depending on the facility and inclusions. Many clubs offer seasonal memberships for part-time residents. Court hire for non-members usually costs 10-25 euros per hour, with coaching from 30-60 euros per session.', 2),
('guide', 'best-tennis-clubs-calvia', 'Can I play tennis year-round in Calvia?', 'Absolutely. The mild Mediterranean climate makes Calvia ideal for year-round tennis. Most clubs have outdoor courts that are playable in all seasons, and some facilities also have covered or indoor courts for rainy days. Summer mornings and late afternoons are the most popular times.', 3),

('guide', 'professional-services-calvia-guide', 'What professional services are available for expats in Calvia?', 'Calvia has a comprehensive range of professional services including lawyers, accountants, tax advisors, IT consultants, translators, architects, interior designers, and business consultants. Many professionals are bilingual or multilingual, serving the large international community.', 1),
('guide', 'professional-services-calvia-guide', 'Do I need a Spanish-speaking professional?', 'While many professionals speak English and other languages, having someone who is fluent in Spanish is essential for dealing with local authorities, legal documents, and tax filings. Most international-facing firms offer services in multiple languages.', 2),
('guide', 'professional-services-calvia-guide', 'How do I find a trusted professional in Calvia?', 'Personal recommendations are highly valued in the expat community. Calvia.app lists verified local professionals with reviews. For legal and financial services, check that practitioners are registered with the appropriate Spanish professional bodies (Colegio de Abogados, etc.).', 3),

('guide', 'yachting-boat-rentals-calvia-guide', 'What marinas can I use in Calvia?', 'Calvia has several excellent marinas including Port Adriano (a luxury marina designed by Philippe Starck), Puerto Portals (one of the Mediterranean top marinas), and Club Nautico Santa Ponsa. Each offers different facilities, mooring sizes, and price ranges.', 1),
('guide', 'yachting-boat-rentals-calvia-guide', 'Can I live on my boat in a Calvia marina?', 'Living aboard is technically possible but heavily regulated. Most marinas require special liveaboard permits, which are limited in number. You will also need to register a local address for tax purposes. Marina fees for long-term berths can be significant, especially at premium locations.', 2),
('guide', 'yachting-boat-rentals-calvia-guide', 'What types of boats can I rent without experience?', 'Small motorboats under 6 metres with engines up to 15 HP can be rented without any license. For anything larger, opt for a skippered charter where an experienced captain handles the navigation while you enjoy the ride. Kayaks and paddleboards are also available at many coastal points.', 3),

('guide', 'family-activities-calvia', 'What are the best family-friendly beaches in Calvia?', 'Palmanova and Santa Ponsa beaches are ideal for families with shallow, calm waters, lifeguards, and nearby amenities. Playa de Magaluf is also family-friendly during the day. For quieter options, Cala Vinyes and Portals Vells offer beautiful coves with clear waters.', 1),
('guide', 'family-activities-calvia', 'Are there activities for children during the off-season?', 'Yes, many activities run year-round including indoor play centres, swimming pools, horse riding, climbing walls, and cultural workshops. The mild winter climate also allows for hiking, cycling, and outdoor play most days. Local sports clubs offer children programs throughout the year.', 2),
('guide', 'family-activities-calvia', 'Is Calvia a good place to raise children as an expat?', 'Calvia is very popular with international families. The area has excellent international schools, a safe environment, outdoor lifestyle, and a welcoming expat community. Children benefit from the multilingual environment and Mediterranean culture while enjoying a high quality of life.', 3);
