/*
  # Seed FAQs for guides missing them - Batch 2

  1. Changes
    - Adds 3 FAQs each for the remaining 13 guides that have zero FAQ entries
    - Covers: Tax/Accounting, Education, Hotels Portals Nous, Beaches,
      Mountain Hikes, Hairdressers, Cafes, Health Clinics, Pet Services,
      Golf, Padel, Expat Living, Beauty Salons

  2. Impact
    - All 48 guides now have FAQ sections
    - Complete FAQ coverage improves SEO and user experience
*/

INSERT INTO faqs (page_type, page_slug, question, answer, display_order) VALUES
('guide', 'tax-accounting-services-calvia-guide', 'Do I need a Spanish tax advisor as an expat?', 'Yes, strongly recommended. Spanish tax rules are complex, especially for non-residents and new residents. Issues like the Beckham Law (special tax regime for inpatriates), wealth tax, and foreign asset reporting require specialized knowledge. Mistakes can result in significant penalties.', 1),
('guide', 'tax-accounting-services-calvia-guide', 'When is the Spanish tax filing deadline?', 'The annual income tax return (Declaracion de la Renta) must be filed between April and June for the previous tax year. Quarterly VAT returns (if self-employed) are due in January, April, July, and October. The Modelo 720 foreign asset declaration is due by the end of March.', 2),
('guide', 'tax-accounting-services-calvia-guide', 'How much do accounting services cost in Calvia?', 'Basic annual tax filing for individuals typically costs 100-300 euros. Self-employed quarterly filings range from 50-150 euros per quarter. Full business accounting packages start from around 150-400 euros monthly depending on complexity and transaction volume.', 3),

('guide', 'education-calvia-guide', 'What school options are there for expat children in Calvia?', 'Calvia offers Spanish public schools, concertado (semi-private) schools, and international private schools. International schools follow British, German, or IB curricula. The area is well served by several top-rated international schools within a short drive.', 1),
('guide', 'education-calvia-guide', 'At what age do children start school in Spain?', 'Compulsory education in Spain starts at age 6 (primary school). However, most children attend pre-school (educacion infantil) from age 3. Nurseries accept children from a few months old. International schools often have their own age entry requirements aligned with their home country system.', 2),
('guide', 'education-calvia-guide', 'Are there language courses available for adults in Calvia?', 'Yes, several language schools offer Spanish courses for adults at all levels, from beginner to advanced. You can also find English, German, and other language courses. Formats include intensive courses, evening classes, private tutoring, and conversation groups.', 3),

('guide', 'best-hotels-portals-nous-bendinat', 'What makes Portals Nous and Bendinat special for a hotel stay?', 'These twin areas offer the most exclusive residential atmosphere in Calvia. Nestled between pine-forested hills and the Mediterranean, they combine luxury living with proximity to Puerto Portals marina, fine dining, designer boutiques, and some of the best beaches on the island.', 1),
('guide', 'best-hotels-portals-nous-bendinat', 'What is the best time to visit Portals Nous?', 'The area is beautiful year-round. Peak season (June-September) offers the best beach weather and a vibrant social scene. Spring (April-May) and autumn (October-November) are ideal for those seeking pleasant weather with fewer crowds and lower hotel rates.', 2),
('guide', 'best-hotels-portals-nous-bendinat', 'Are there budget-friendly options in the area?', 'Portals Nous and Bendinat are premium areas, so budget options are limited. Nearby Palmanova and Costa den Blanes offer more affordable accommodation while still being within a short drive. Booking outside peak season also reduces rates significantly at all price levels.', 3),

('guide', 'best-beaches-calvia', 'How many beaches are there in Calvia?', 'Calvia boasts over 30 beaches and coves along its 54 kilometres of coastline. These range from large sandy beaches with full facilities like Palmanova and Magaluf to hidden rocky coves like Portals Vells and Cala Figuera that require a short walk to reach.', 1),
('guide', 'best-beaches-calvia', 'Are Calvia beaches safe for swimming?', 'Yes, most main beaches have lifeguards during summer months, clear flag systems indicating conditions, and gentle slopes ideal for families. The Mediterranean waters are calm with minimal tidal variation. Always check the flag status and swim between the designated markers.', 2),
('guide', 'best-beaches-calvia', 'Which beaches have the best facilities?', 'Palmanova, Santa Ponsa, Magaluf, and Peguera have the most complete facilities including sunbed rentals, beach bars, showers, toilets, and disabled access. Smaller coves like Cala Vinyes and El Toro have basic facilities. Remote coves typically have no facilities at all.', 3),

('guide', 'mountain-summit-hikes-calvia', 'What is the highest peak accessible from Calvia?', 'Puig de Galatzo at 1,026 metres is the most prominent summit in the Calvia municipality. The hike from Es Capdella is approximately 12 km round trip and takes 4-5 hours. Other popular summits include Na Bauza and the Serra de na Burguesa ridge walks.', 1),
('guide', 'mountain-summit-hikes-calvia', 'What equipment do I need for mountain hikes near Calvia?', 'Essential gear includes sturdy hiking boots with ankle support, at least 2 litres of water per person, sun protection, a hat, layered clothing, and a trail map or GPS. For summit hikes, bring a headlamp, first aid kit, and extra food. Mobile phone reception can be patchy in valleys.', 2),
('guide', 'mountain-summit-hikes-calvia', 'Are there guided hiking tours available?', 'Yes, several companies offer guided hikes ranging from easy coastal walks to challenging mountain ascents. Guided tours typically cost 30-60 euros per person and include transport, route guidance, and local ecological and historical information. Group sizes are usually kept small.', 3),

('guide', 'hairdressers-calvia-guide', 'Do hairdressers in Calvia speak English?', 'Many hairdressers in Calvia are multilingual due to the large international community. English, German, and Scandinavian languages are commonly spoken alongside Spanish. It is always worth checking when booking, but most salons in tourist and expat areas have English-speaking staff.', 1),
('guide', 'hairdressers-calvia-guide', 'How much does a haircut cost in Calvia?', 'A standard women haircut ranges from 25-60 euros depending on the salon and stylist. Men haircuts typically cost 15-30 euros. Colour treatments, highlights, and specialized services are priced additionally. Premium salons in areas like Portals Nous charge higher rates.', 2),
('guide', 'hairdressers-calvia-guide', 'Do I need to book an appointment?', 'Booking in advance is recommended, especially at popular salons and during summer months. Many salons accept online bookings through their websites or social media. Some smaller barbershops and salons do accept walk-ins, particularly during quieter periods.', 3),

('guide', 'best-cafes-calvia', 'Where can I find specialty coffee in Calvia?', 'The specialty coffee scene has grown significantly in recent years. You will find excellent third-wave coffee shops in Palmanova, Santa Ponsa, and Portals Nous offering single-origin beans, pour-over methods, and artisan pastries. Many cafes roast their own beans or source from local Mallorcan roasters.', 1),
('guide', 'best-cafes-calvia', 'Do cafes in Calvia have good WiFi for remote work?', 'Many modern cafes offer free WiFi suitable for remote work, and some have become popular digital nomad spots with dedicated work-friendly spaces, power outlets, and quiet areas. Coworking spaces are also emerging in the area for those needing a more professional setup.', 2),
('guide', 'best-cafes-calvia', 'What are typical cafe hours in Calvia?', 'Most cafes open between 7:30 and 9:00 AM and close between 5:00 and 7:00 PM. Some stay open later during summer. Brunch spots typically serve until early afternoon. During winter, some seasonal cafes may have reduced hours or close temporarily.', 3),

('guide', 'health-clinics-calvia-guide', 'Is healthcare good in the Calvia area?', 'Healthcare in Calvia is excellent. The area has modern private clinics with multilingual staff, well-equipped public health centres, and is within 20-30 minutes of several major hospitals in Palma. Private health insurance provides access to English-speaking specialists with short waiting times.', 1),
('guide', 'health-clinics-calvia-guide', 'Do I need private health insurance in Calvia?', 'If you are a resident registered with social security, you have access to the Spanish public healthcare system. However, many expats choose private insurance for shorter waiting times, English-speaking doctors, and access to private hospitals. Private insurance typically costs 50-150 euros per month.', 2),
('guide', 'health-clinics-calvia-guide', 'Are there English-speaking doctors in Calvia?', 'Yes, many doctors and clinics in Calvia cater specifically to the international community and have English-speaking staff. Some clinics also offer services in German, Swedish, and other languages. Calvia.app lists clinics with language information on their profiles.', 3),

('guide', 'pet-services-calvia-guide', 'Is Calvia a pet-friendly area?', 'Calvia is quite pet-friendly with many parks, walking trails, and outdoor spaces. Several restaurants and cafes welcome dogs on their terraces. There are designated dog beaches in the area, and most veterinary services are of high quality with multilingual staff.', 1),
('guide', 'pet-services-calvia-guide', 'What do I need to bring a pet to Mallorca?', 'EU pets need a pet passport, microchip, and up-to-date rabies vaccination. From outside the EU, additional requirements may include a health certificate and blood tests. On arrival, register your pet with a local vet who can advise on any additional treatments needed for the Mediterranean climate.', 2),
('guide', 'pet-services-calvia-guide', 'How much do veterinary services cost in Calvia?', 'A standard vet consultation costs 30-60 euros. Annual vaccinations and check-ups run 60-120 euros. Pet insurance is available from around 15-40 euros per month. Dog grooming services typically cost 25-60 euros depending on the breed and service. Emergency care is available 24/7 in Palma.', 3),

('guide', 'best-golf-courses-calvia', 'How many golf courses are there near Calvia?', 'Calvia and the surrounding area have over 20 golf courses within a 30-minute drive, making it one of the best golfing destinations in the Mediterranean. Courses range from championship-level designs by Jack Nicklaus and Robert Trent Jones to more relaxed resort courses.', 1),
('guide', 'best-golf-courses-calvia', 'What is the green fee for golf in Calvia?', 'Green fees vary widely from 40-60 euros at more accessible courses to 100-200 euros at championship courses. Many courses offer twilight rates, multi-round packages, and seasonal discounts. Annual memberships provide significant savings for regular players and often include practice facilities.', 2),
('guide', 'best-golf-courses-calvia', 'Can I play golf year-round in Mallorca?', 'Yes, Mallorca is an excellent year-round golf destination. The mild winters (average 15 degrees) mean courses stay green and playable all year. Summer can be hot, so early morning tee times are popular from June to August. Spring and autumn offer the ideal playing conditions.', 3),

('guide', 'best-padel-clubs-calvia', 'What is padel and why is it so popular in Calvia?', 'Padel is a racquet sport played in doubles on an enclosed court smaller than a tennis court. It is the fastest-growing sport in Spain and incredibly popular in Calvia. It is easier to learn than tennis, highly social, and provides an excellent workout. Courts are widely available across the region.', 1),
('guide', 'best-padel-clubs-calvia', 'How much does it cost to play padel in Calvia?', 'Court hire typically costs 8-20 euros per person per hour. Many clubs offer membership packages from 30-80 euros per month that include court bookings, lessons, and social events. Beginner group lessons usually cost 10-20 euros per session. Rackets can be rented for a few euros.', 2),
('guide', 'best-padel-clubs-calvia', 'Can beginners play padel?', 'Absolutely. Padel is known for being accessible to beginners. The smaller court, underhand serve, and wall bounces make it easier to rally quickly. Most clubs offer beginner clinics and intro sessions. Within a few sessions, most people can play enjoyable matches.', 3),

('guide', 'living-in-calvia-expat-guide', 'What is the cost of living in Calvia compared to other parts of Mallorca?', 'Calvia is one of the more affluent areas of Mallorca, so costs tend to be higher than the island average, particularly for housing. A couple can live comfortably on 2,500-3,500 euros per month including rent, while premium lifestyles in areas like Portals Nous or Bendinat require significantly more.', 1),
('guide', 'living-in-calvia-expat-guide', 'What do I need to become a resident in Calvia?', 'EU citizens need to register on the Foreign Nationals Registry (obtaining a green NIE card) after 3 months. Non-EU citizens need a visa or residence permit. All residents should register on the padron (municipal census) at the Calvia town hall, which gives access to local services.', 2),
('guide', 'living-in-calvia-expat-guide', 'Is it easy to meet other expats in Calvia?', 'Very easy. Calvia has one of the largest international communities in Mallorca. There are numerous social clubs, networking groups, sports clubs, and community events. Facebook groups, local associations, and venues like beach clubs and restaurants serve as natural meeting points.', 3),

('guide', 'beauty-salons-calvia-guide', 'What beauty treatments are popular in Calvia?', 'Popular treatments include facials, manicures and pedicures, laser hair removal, body wraps, and anti-aging treatments. Many salons also offer advanced treatments like microneedling, LED therapy, and chemical peels. The wellness culture in Calvia means high demand for holistic beauty services.', 1),
('guide', 'beauty-salons-calvia-guide', 'Are beauty products in Calvia salons high quality?', 'Most established salons use internationally recognized professional brands. Many also incorporate locally made Mallorcan natural products using ingredients like olive oil, almond oil, and Mediterranean herbs. Ask your salon about the brands they use if you have specific preferences or sensitivities.', 2),
('guide', 'beauty-salons-calvia-guide', 'How much do beauty treatments cost in Calvia?', 'A basic manicure starts from 15-25 euros, while gel or SNS nails cost 30-50 euros. Facials range from 40-120 euros depending on the treatment. Full-body massage and spa packages start from 60 euros. Premium salons in upscale areas charge at the higher end of these ranges.', 3);
