/*
  # Seed FAQs for 7 categories missing them

  1. Changes
    - Adds 4 FAQs each for 7 category pages that currently have zero FAQ entries
    - Categories: Hiking Trails, Yoga & Pilates, Banks & Finance,
      Beaches & Coves, Lawyers & Legal Services, Bike Trails, Pharmacies

  2. Impact
    - All category pages now display FAQ sections
    - Complete FAQ coverage improves SEO with structured Q&A content
*/

INSERT INTO faqs (page_type, page_slug, question, answer, display_order) VALUES
('category', 'hiking-trails', 'What difficulty levels of hiking trails are available in Calvia?', 'Calvia offers trails for all levels. Easy coastal walks along the cliff paths between Palmanova and Portals Vells suit beginners. Moderate routes through the Serra de na Burguesa provide variety. Challenging mountain ascents like Puig de Galatzo (1,026m) test experienced hikers.', 1),
('category', 'hiking-trails', 'When is the best time to hike in Calvia?', 'Autumn (September-November) and spring (March-May) offer ideal conditions with mild temperatures and green landscapes. Winter hiking is pleasant on sunny days. Summer is best avoided for long hikes due to heat, though early morning coastal walks remain enjoyable.', 2),
('category', 'hiking-trails', 'Are hiking trails in Calvia well marked?', 'Main routes are generally well marked with waypoints, signposts, and painted trail markers. The GR221 long-distance path is excellently maintained. Shorter local trails vary in quality. A good trail map or GPS app is recommended, especially for mountain and lesser-known routes.', 3),
('category', 'hiking-trails', 'Do I need any permits to hike in Calvia?', 'Most trails are freely accessible. Some finca (estate) trails require permission. During high fire risk periods in summer, certain forest and mountain areas may be temporarily closed by the authorities. Always check local restrictions before heading out.', 4),

('category', 'yoga-pilates', 'What is the difference between yoga and pilates?', 'Yoga focuses on flexibility, mindfulness, and breath work through held poses. Pilates emphasizes core strength, alignment, and controlled movements, often using equipment like reformers. Both improve posture and reduce stress. Many people practice both for complementary benefits.', 1),
('category', 'yoga-pilates', 'Are outdoor yoga classes available in Calvia?', 'Yes, outdoor yoga is very popular in Calvia. Many instructors offer beach yoga, garden sessions, and rooftop classes, particularly during the warmer months. Sunrise and sunset sessions by the sea are especially popular with both residents and visitors.', 2),
('category', 'yoga-pilates', 'Do studios in Calvia offer reformer pilates?', 'Several studios in Calvia offer reformer pilates alongside mat-based classes. Reformer sessions provide resistance-based training with specialized equipment. Classes are typically smaller and may cost slightly more than mat classes due to equipment requirements.', 3),
('category', 'yoga-pilates', 'Can I find English-speaking yoga instructors in Calvia?', 'Absolutely. The international community means many instructors teach in English, often alongside Spanish and German. Some studios offer classes in multiple languages. Check individual studio profiles on Calvia.app for language information.', 4),

('category', 'banks-finance', 'Which banks operate in Calvia?', 'Major Spanish banks with branches in Calvia include CaixaBank, BBVA, Banco Santander, and Bankinter. International residents often choose CaixaBank or BBVA for their English-language services and international transfer capabilities. Many branches are located in Palmanova, Santa Ponsa, and Peguera.', 1),
('category', 'banks-finance', 'Can I open a bank account in Spain as a non-resident?', 'Yes. You will need your passport, NIE (foreigner identification number), and proof of address (from your home country is accepted). Non-resident accounts have some limitations compared to resident accounts. Once you obtain residency, you can convert to a resident account.', 2),
('category', 'banks-finance', 'What financial services do expats typically need in Calvia?', 'Common needs include a Spanish bank account, international money transfers, mortgage services for property purchases, investment advice, pension planning, tax optimization, and insurance. Many financial advisors in the area specialize in cross-border financial planning for expats.', 3),
('category', 'banks-finance', 'Are there English-speaking financial advisors in Calvia?', 'Yes, many financial advisory firms in Calvia cater specifically to the international community with multilingual staff. Services include wealth management, pension transfers, tax planning, and investment advice tailored to expat circumstances.', 4),

('category', 'beaches', 'How many beaches does Calvia have?', 'Calvia municipality has over 30 beaches and coves spread along 54 kilometres of Mediterranean coastline. These range from wide sandy beaches with full services to hidden rocky coves accessible only on foot or by boat.', 1),
('category', 'beaches', 'Are there lifeguards on Calvia beaches?', 'Yes, the main public beaches have lifeguard services from approximately June through September. Flags indicate swimming conditions: green (safe), yellow (caution), and red (no swimming). Smaller coves typically do not have lifeguard services.', 2),
('category', 'beaches', 'Which Calvia beaches are best for children?', 'Palmanova, Santa Ponsa, and Peguera beaches are excellent for families with shallow entry, calm waters, and nearby facilities. Magaluf beach is also family-friendly during the daytime. These beaches have sunbed rentals, restaurants, and public amenities within easy reach.', 3),
('category', 'beaches', 'Are there dog-friendly beaches in Calvia?', 'Calvia has designated dog beaches that operate mainly outside the peak summer months. During summer, dogs are typically allowed on beaches before 9 AM and after 7 PM. Check the specific rules for each beach as regulations can change seasonally.', 4),

('category', 'lawyers-legal', 'Why might I need a lawyer in Calvia?', 'Common reasons include property purchases and sales, setting up a business, immigration and residency paperwork, inheritance planning, contract disputes, and navigating Spanish bureaucracy. Having a lawyer familiar with both Spanish and international law is particularly valuable for expats.', 1),
('category', 'lawyers-legal', 'How much do legal services cost in Calvia?', 'Initial consultations often cost 50-150 euros or are sometimes free. Property conveyancing typically costs 1-1.5 percent of the property value. Hourly rates for general legal work range from 100-250 euros depending on the complexity and the lawyer experience.', 2),
('category', 'lawyers-legal', 'Do I need a Spanish lawyer for property purchases?', 'It is strongly recommended. A Spanish lawyer (abogado) will conduct due diligence on the property, check for debts or charges, review the contract, and represent you at the notary. They protect your interests in ways that the notary (who is neutral) does not.', 3),
('category', 'lawyers-legal', 'Are there English-speaking lawyers in Calvia?', 'Yes, many law firms in Calvia specialize in serving the international community and have bilingual or multilingual lawyers. Some firms focus specifically on expat legal needs including property law, tax law, immigration, and cross-border inheritance matters.', 4),

('category', 'bike-trails', 'What types of cycling are popular in Calvia?', 'Road cycling is the most popular, with professional teams regularly training on the smooth, quiet roads. Mountain biking is growing with trails through the Serra de Tramuntana foothills. Casual cycling along the coastal promenades and through villages is also very accessible.', 1),
('category', 'bike-trails', 'Can I rent bikes in Calvia?', 'Yes, numerous bike rental shops operate throughout Calvia, particularly in Santa Ponsa, Palmanova, and Peguera. Options range from basic city bikes to high-end carbon road bikes and electric mountain bikes. Rental prices start from about 10-15 euros per day for standard bikes.', 2),
('category', 'bike-trails', 'Is Calvia good for beginner cyclists?', 'The coastal areas around Palmanova, Magaluf, and Santa Ponsa are quite flat and ideal for beginners, with dedicated cycle paths in many areas. For those wanting a gentle challenge, the road to Es Capdella offers beautiful scenery with moderate gradients.', 3),
('category', 'bike-trails', 'When is the best time for cycling in Calvia?', 'Spring (February-May) and autumn (September-November) offer the best cycling conditions with comfortable temperatures and low winds. Professional teams train here from January. Summer riding is best done early morning before the heat. Winter is mild but can be wet.', 4),

('category', 'pharmacies', 'Are pharmacies easy to find in Calvia?', 'Yes, pharmacies (farmacias) are well distributed across all the main villages of Calvia. They are identified by a green cross sign, often illuminated. Most shopping areas and town centres have at least one pharmacy within walking distance.', 1),
('category', 'pharmacies', 'Do pharmacies in Calvia have English-speaking staff?', 'Many pharmacies in tourist and expat areas have staff who speak English and other languages. Pharmacists in Spain are highly trained medical professionals who can provide advice on minor ailments, recommend over-the-counter medications, and help you find the Spanish equivalent of medications from your home country.', 2),
('category', 'pharmacies', 'What are pharmacy opening hours in Calvia?', 'Standard hours are typically 9:30 AM to 1:30 PM and 5:00 PM to 8:00 PM, Monday to Friday, with Saturday mornings. A rotating duty pharmacy (farmacia de guardia) is always open 24/7 for emergencies. The duty schedule is posted on every pharmacy door and available online.', 3),
('category', 'pharmacies', 'Can I get my regular medication at pharmacies in Calvia?', 'Most common medications are available in Spain, though brand names may differ. Bring your prescription or a letter from your doctor listing the generic names. Spanish pharmacists can often dispense many medications that require prescriptions in other countries. For controlled substances, a Spanish prescription is required.', 4);
